### ISSUE TITLE
Consider re-exporting some types

### ISSUE THREAD

**Issue by uint** [ndebuhr/sim#4]
Adding some `pub use` lines in `models/mod.rs` could make things a little nicer for importing. There are probably other places.

`models::exclusive_gateway::ExclusiveGateway` could become `models::ExclusiveGateway` and `models::model::Model` could become `models::Model`.

[Reference](https://doc.rust-lang.org/nightly/book/ch14-02-publishing-to-crates-io.html#exporting-a-convenient-public-api-with-pub-use)

**Comment by ndebuhr** [comment]
Released in v0.6.0
https://github.com/ndebuhr/sim/releases/tag/v0.6.0
